### ISSUE TITLE
[cPP Correction] FAU_STG* Cleanup

### ISSUE THREAD

**Issue by kenji-lightship** [ND-iTC/Documents#104]
**Provide the location of the issue**
There are multiple issues with the FAU_STG* SFRs:
1.	FAU_STG_EXT.1/LocSpace is not an iteration of FAU_STG_EXT.1, it is a completely separate SFR.
2.	There are many references to FAU_STG_EXT.1.3 which does not exist
3.	The ECD for FAU_STG_EXT.1 does not match the SFR.
4.	The requirements for FAU_STG_EXT.1/LocSpace vs. FAU_STG.1 are unclear as initially pointed out in RFI202102. FAU_STG_EXT.1/LocSpace does not explicitly require the protection of audit record, but this is tested in the SD. FAU_STG.1 requires protection of audit records, but the test requires the admin to be able to manage/delete the records.
5.	SD Section 2.1.4.3, Test 4 references FAU_STG_EXT.1.3 Test 2 which does not exist.

**Describe the solution you'd like**
•	combine FAU_STG_EXT.1 and FAU_STG_EXT.1/LocSpace. I don’t see a reason they need to be separate and it avoids having to renumber SFRs.
•	FAU_STG.1 should be made mandatory or a new element should be added to FAU_STG_EXT.1 to specify the protection of audit data. Management/deletion of audit data should be moved from the FAU_STG.1 test to an FMT_SMF.1 selection and test.
•	A pass thought the cPP and SD needs to be made to ensure references to FAU_STG_EXT.1.* (I noted FAU_STG_EXT.1.2 and FAU_STG_EXT.1.3) are referencing the correct components and tests.

**Comment by dundiddat** [comment]
Responding to Kenji's bulleted suggestions in the issue description:

* 1st bullet: I disagree.  FAU_STG_EXT.1 is related to use of a remote audit server while FAU_STG_EXT.1/LocSpace is related to local storage.

* 2nd bullet: I disagree.  FAU_STG.1 should not be mandatory because local storage is not mandatory.  I also don't agree that it should be merged into FAU_STG_EXT.1/LocSpace because the SFR elements of FAU_STG.1 match what's in CC Part 2, so they don't need to be in an extended SFR.  I also disagree that the testing should be moved into FMT_SMF.1 because the resulting test description under FMT_SMF.1 would probably just refer back to FAU_STG.1 by suggesting the test can be performed as part of testing for FAU_STG.1.

* 3rd bullet: Agreed.

**Comment by dundiddat** [comment]
Responding to Kenji's numbered items in the issue description:

1. Agreed, the SFRs are separate, not iterations.  We could rename FAU_STG_EXT.1 to FAU_STG_EXT.1/Remote.

2. Agreed.  Necessary changes include...
* In PP section A.2.1.2: Change FAU_STG_EXT.1.3 to FAU_STG_EXT.1.3/LocSpace.
* In Application Note 121: Change from, "... refers to **the different options for selection and assignments in SFRs FAU_STG_EXT.1.3 and FAU_STG_EXT.2**."  Change to, "... refers to **any administratively configurable selection or assignments in any FAU_STG_EXT.x SFR**."

3. Agreed.  Remove FAU_STG_EXT.1.3 from section C.1.2.1.

4.A. (FAU_STG_EXT.1/LocSpace). Agreed. In SD section 2.1.4.3...
* Remove Test 1 (note, this will renumber the subsequent tests).

4.B (FAU_STG.1). Agreed.  Modify the SD section 3.1.1.3 to...
* Replace Test 1 with, "Test 1: The evaluator shall **attempt to** access the audit trail without authentication as Security Administrator (either by authentication as a non-administrative user, if supported, or without authentication at all) and attempt to modify and delete the audit records. The evaluator shall verify that these attempts fail."  **<REMOVE-REMAINING-SENTENCES>**
* Replace Test 2 with, "Test 2: The evaluator shall access the audit trail as an authorized administrator and attempt to delete audit records **(if supported by the TOE, and to the extent described in the TSS)**. **<REMOVE-SENTENCE>** The evaluator shall verify that only the records authorized for deletion are deleted."

5. Agreed. In SD section 2.1.4.3 (for FAU_STG_EXT.1.3/LocSpace)...
* In Test 3, change all references from FAU_STG_EXT.1.3 to FAU_STG_EXT.1.3/LocSpace.
* In Test 4, remove most of the first sentence (because the part about an external audit server is applicable only to FAU_STG_EXT.1) and make other changes (e.g. changing test numbers after removing the original Test 1), so it should now read, "Test 4: For distributed TOEs, for the local storage according to FAU_STG_EXT.1.2 **the Test 1** specified above shall be applied to all TOE components that store audit data locally. For all TOE components that store audit data locally and comply with FAU_STG_EXT.2/LocSpace **Test 2** specified above shall be applied. The evaluator shall verify that the transfer of audit data to an external audit server is implemented."
* In FAU_STG_EXT.1 (remote), add test 2 (moving a sentence from FAU_STG_EXT.1/LocSpace Test 4), "Test 2: For distributed TOEs, Test 1 defined above should be applicable to all TOE components that forward audit data to an external audit server."

**Comment by kenji-lightship** [comment]
@dundiddat's comments on the recommendations
1st bullet: FAU_STG_EXT.1.2 is about storage of audit records. Maybe this should be moved to FAU_STG_EXT.1/LocSpace to separate transmission and storage as you mention. I don't have a preference on whether they are combined or separate.
2nd bullet: Non-volatile storage is not required, but FAU_STG_EXT.1/LocSpace is mandatory and requires at least non-persistent local buffering. If FAU_STG.1 remains optional, there's the odd question (it's not a new for v3.0) of whether TOEs need to protection audit records from unauthorized deletion and modification since the SFR is not required. Since this is not a new issue, it can be "no change" for now.

I don't think FAU_STG_EXT.1/Remote and FAU_STG_EXT.1/LocSpace would meet the requirements for iteration. They seem to be distinct functions that wouldn't have a shared ECD definition.

**Comment by tamcompton** [comment]
1. We could also name the SFR FAU_STG_EXT.1/RemSpace to be consistent with /LocSpace.  In any case I agree a name change.
2. Agreed with Ken
3. I don't think the Remote and Local versions are iterations. They are separate SFRs.
4. I don't think we want to qualify the administrator role.  We haven't done that in other places and it adds a complexity that we haven't introduced across other SFRs
5. Agree with Ken

**Comment by KSinitski** [comment]
I think distinction between Security Administrators (i.e., defined role) and administrator (i.e., categorically any user with access to any management interface) categorically changes the meaning of this requirement and ought to be clarified.

**Comment by dundiddat** [comment]
> * Replace Test 2 with, "Test 2: The evaluator shall access the audit trail as an authorized administrator and attempt to delete audit records **(if supported by the TOE, and to the extent described in the TSS)**.  The evaluator shall verify that only the records authorized for deletion are deleted."

Per comment from @KSinitski, will use this text for part if item 4.B to use "Security Administrator" instead of "administrator":
So, will... 
Replace Test 2 with, "Test 2: The evaluator shall access the audit trail as an **authenticated Security Administrator** and attempt to delete audit records **(if supported by the TOE, and to the extent described in the TSS)**. The evaluator shall verify that only the records authorized for deletion are deleted."
