### ISSUE TITLE
[cPP Correction] DTLSS Support for Secure Renegotiation

### ISSUE THREAD

**Issue by kenji-lightship** [ND-iTC/Documents#116]
**What is the correction request for the cPP? Please describe.**
FCS_TLSS_EXT.3 has been added for TLS, but there is not a corresponding DTLS SFR. Should there be?

**Comment by plughy2** [comment]
Yes a corresponding FCS_DTLS_EXT.3 needs to be added.

**Comment by ianhallbc** [comment]
Makes sense to have the renegotiation component for both

**Comment by kr15tyk** [comment]
@kenji-lightship Can you review the following SFR for accuracy?

FCS_DTLSS_EXT.3 DTLS Server Support for secure renegotiation (DTLSv1.2 only)

FCS_DTLSS_EXT.3.1 The product shall support secure renegotiation in accordance with RFC 5746 by always including the ”renegotiation_info” extension in ServerHello messages.

Application Note #TBD

This component may only be claimed for DTLS 1.2 but not DTLS 1.3.

RFC 5746 defines an extension to DTLS that binds renegotiation handshakes to the cryptography in the original handshake in order to prevent an attack in which the attacker forms a TLS connection with the target server, injects content of his choice, and then splices in a new TLS connection from a client. The server treats the client’s initial TLS handshake as a renegotiation and thus believes that the initial data transmitted by the attacker is from the same entity as the subsequent client data.

**Comment by kr15tyk** [comment]
@ND-iTC/tls @ouarak @plughy2 @a-kandiah @michaelvogelatsec  @kenji-lightship
I also noticed that there is an SFR for FCS_TLSC_EXT.3, but not one for FCS_DTLSC_EXT.3. Should this be added?

**Comment by plughy2** [comment]
There should be an SFR for FCS_DTLSC_EXT.3.   Also the Test Activities for FCS_TLSS_EXT.3 and FCS_TLSC_EXT.3 should be respectively copied to FCS_DLSS_EXT.3 and FCS_DLSC_EXT.3 in the Supporting Document. 

The SFR for FCS_DTLSC_EXT.3 would read:

FCS_DTLSC_EXT.3 DTLS Client Support for secure renegotiation (DTLSv1.2 only)

FCS_DTLSC_EXT.3.1 The product shall support secure renegotiation through use of the “renegotiation_info” TLS extension in accordance with RFC 5746.

Application Note xx

This component may only be claimed for DTLS 1.2 but not DTLS 1.3.

RFC 5746 defines an extension to TLS that binds renegotiation handshakes to the cryptography in the original handshake.

When performing secure renegotiation, the ”renegotiation_info” extension must be presented by the server initiating renegotiation, so the client must support use of this extension.

When signaling support for secure renegotiation, the client may present either the ”renegotiation_info” extension or the signaling cipher suite value TLS_EMPTY_RENEGOTIATION_INFO_SCSV in the initial ClientHello message. (A signaling cipher suite value (SCSV) is presented as a cipher suite, but its only purpose is to provide other information and not to advertise support for a cipher suite.) The TLS_EMPTY_RENEGOTIATION_INFO_SCSV signaling cipher suite value exists as an alternative to presenting the ”renegotation_info” extension so that TLS server implementations that immediately terminate the connection when they encounter any extension they do not understand can still proceed with a connection. The client may still choose to reject the connection later, if it insists upon renegotiation support and the server does not support it.
