### ISSUE TITLE
Minor Issues [cPP Correction]

### ISSUE THREAD

**Issue by xahun** [ND-iTC/Documents#125]
Section 2.1 - the link doesn't seem to exist 404 error.

Table 1 doesn't identify FAU_STG_EXT.1/LocSpace and it seems like it should.

Figure 10 - the note under figure 10 references figure 8 instead of figure 10.

Figure 12 - the note before figure 12 references figure 10 and maybe that should be figure 12.

Section 6.7 - FPT_STM_EXT.1 (section 6.7.4) is ordered after the requirements FPT_TST_EXT.1 (section 6.7.2), and FPT_TUD_EXT.1 (section 6.7.3).  These should be sorted alphabetically.

Table 5 - the last three rows identifiy "None." as the requirement and a requirement is identified as additional content.  

Application Notes 73, 99, 100, and 106 have unlabelled tables while all other tables have labels.  It seems like this should be consistent and they should ahve labels (e.g., for easy reference).

**Comment by Kirky-J** [comment]
The link is currently broken due to the fact that points to a document which only exists on the 'Development' branch. Once this branch is merged in to the 'Main' branch, the Allowed_With list will also become available and the link will work.

FAU_STG_EXT.1/LocSpace does appear to be missing and has been added in to Table 1

Incorrect reference to Figure 8 in Case 4 (Distributed TOEs) updated to correctly reference Figure 10

Incorrect reference to Figure 10 in Section 3.3 updated to correctly reference Figure 12

Section 6.7 reordered to be alphabetical.

Table 5 corrected and alignment is now as it should be.

**Comment by Kirky-J** [comment]
Table labels added to tables in the Application Notes 73, 99, 100, and 106. Old table references updated (Table numbers changed from 6 -> 10, 7->11, 8->12). List of tables updated to include links to new tables.

All fixed in editorial-cPP-200123
