### ISSUE TITLE
FCS_TLSC_EXT.1.1 - Clarification of  the deprecation of TLSv1.1 and SHA-1

### ISSUE THREAD

**Issue by Kirky-J** [ND-iTC/Documents#129]
**Location of the issue**
FCS_TLSC_EXT.1.1

In the application note, it states “Even though RFC 5246 mandates implementation of specific ciphers for TLS 1.2, this cPP deprecates use of SHA-1.” Cipher suites with SHA-1 is still allowed. Only TLSv1.1 is deprecated?

**Comment by plughy2** [comment]
The TLSWG agreed that TLS v1.1 would be deprecated in NDcPP v3.0.  One suggestion would be to replace the quoted sentence above with the NDcPP v2.2 text:  "Even though RFC 5246 mandates implementation of specific ciphers, there is no requirement to implement TLS_RSA_WITH_AES_128_CBC_SHA in order to claim conformance to this cPP."

Note issue in #114 with the last sentence in that paragraph.

**Comment by kr15tyk** [comment]
Application note 62 in FCS_DTLSC_EXT.1.1 has the same issue.

**Comment by kr15tyk** [comment]
Agreed to go with Kenji's wording on today's TLSWG call, "There is no requirement to implement ciphersuites the RFCs specify as mandatory in order to claim conformance to this cPP." THis issue will be resolved in issue #114 .
