### ISSUE TITLE
Section 4.1.3.1 T. UNDETECTED_ACTIVITY

### ISSUE THREAD

**Issue by Kirky-J** [ND-iTC/Documents#145]
Under “SFR Rationale:” fourth bullet, FAU_STG_EXT.2/LocSpace and FAU_STG_EXT.3/LocSpace had been replaced with FAU_STG_EXT.2 and FAU_STG_EXT.3 for NDcPPv3.0.  Why?

**Comment by dundiddat** [comment]
Recommendation...
No change to PP/SD.  
Explanation: The SFR names were changed for brevity, and because there's now only one iteration of each FAU_STG_EXT.x.

Note: There may be some usefulness in renaming FAU_STG_EXT.1 to FAU_STG_EXT.1/Remote so that it's name reflects its purpose similar to FAU_STG_EXT.1/LocSpace.   Refer to issue #104 for further discussion of that idea.

**Comment by KSinitski** [comment]
Agreed.

**Comment by dundiddat** [comment]
Closing this issue after discussion in MINT meeting on 2023-02-13.
